[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "anddea/revanced-patches"
rv-brand = "MusicExtended"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "anddea/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "ReVanced Extended"
version = "20.21.37"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=FF181825 -OlightThemeBackgroundColor=FFE6E9EF"
